apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: reservation-app
spec:
  selector:
    app: mysqld-exporter
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104

