apiVersion: v1
kind: Pod
metadata:
  name: prometheus-grafana
  namespace: reservation-app
  labels:
    app: prometheus-grafana
spec:
  containers:
  - name: prometheus
    image: prom/prometheus:latest
    args:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.listen-address=0.0.0.0:9191
    ports:
      - containerPort: 9191
        name: web
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: reservation-app
spec:
  selector:
    app: prometheus-grafana
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191

