apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-app
  namespace: reservation-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-app
  template:
    metadata:
      labels:
        app: reservation-app
    spec:
      containers:
        - name: reservation
          image: default-route-openshift-image-registry.apps-crc.testing/reservation-app/reservation-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "reservationdb"
          
