apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-app
  namespace: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-app
  template:
    metadata:
      labels:
        app: reservation-app
    spec:
      containers:
        - name: reservation
          image: default-route-openshift-image-registry.apps-crc.testing/reservation-app/reservation-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "reservationdb"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: reservation-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
 
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
 
      - job_name: "reservation-app"
        metrics_path: /metrics
        static_configs:
          - targets: ["reservation-app:8080"]








